CREATE DATABASE LIBRARYSOCKET
GO
USE LIBRARYSOCKET
GO
---------------------
CREATE TABLE ACCOUNTS 
(
	USERNAME nchar(20),
    PASSW nchar(50),
	PRIMARY KEY (USERNAME)
)

CREATE TABLE BOOKS 
(
	ID int,
    BOOK_NAME nchar(50),
    CATEGORY nchar(50),
    AUTHORS nchar(100),
    RELEASEYEAR int,
    LINK nchar(50),
	PRIMARY KEY (ID)
)
--------------------
USE QLDT1
DROP DATABASE LIBRARYSOCKET
INSERT INTO ACCOUNTS VALUES ('drwpls', '1234')
INSERT INTO ACCOUNTS VALUES ('account1', '1234')

INSERT INTO BOOKS VALUES (1, 'BOOK_1_NAME', 'CATEGORY_1', 'AUTHOR_1', 2000, 'C:\')
INSERT INTO BOOKS VALUES (2, 'BOOK_2_NAME', 'CATEGORY_2', 'AUTHOR_2', 2001, 'D:\')