CREATE DATABASE LIBRARYSOCKET
GO
USE LIBRARYSOCKET
GO
---------------------
CREATE TABLE ACCOUNTS 
(
	USERNAME varchar(20),
    PASSW varchar(50),
	PRIMARY KEY (USERNAME)
)

CREATE TABLE BOOKS 
(
	ID int,
    BOOK_NAME nvarchar(50),
    CATEGORY nvarchar(50),
    AUTHORS nvarchar(100),
    RELEASEYEAR int,
    LINK varchar(50),
	PRIMARY KEY (ID)
)
--------------------
INSERT INTO ACCOUNTS VALUES ('drwpls', '1234')
INSERT INTO ACCOUNTS VALUES ('account1', '1234')

INSERT INTO BOOKS VALUES (1, 'BOOK_1_NAME', 'CATEGORY_1', 'AUTHOR_1', 2000, 'books\a.txt')
INSERT INTO BOOKS VALUES (3, 'BOOK_1_NAME', 'CATEGORY_1', 'AUTHOR_1', 2000, 'books\b.txt')
INSERT INTO BOOKS VALUES (2, 'BOOK_2_NAME', 'CATEGORY_2', 'AUTHOR_2', 2001, 'books\c.txt')
